version: 0.2

phases:
  install:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - TAG=${COMMIT_HASH:=latest}
      - TEST_FILE=test_result.xml
      - PROJECT_NAME=ConceptMicroservice
      - echo PWD
      - ls -l
      - cd $PROJECT_NAME.UnitTests
      - dotnet restore
  build:
    commands:
      - dotnet test -logger "trx;LogFileName=$TEST_FILE"
artifacts:
    files:
      - 'TestResults/$TEST_FILE'
    name: test_result.$TAG