version: 0.2

env:
  variables:
    REPOSITORY_URI: "028339193837.dkr.ecr.eu-west-1.amazonaws.com/ndla"
    REGION: "eu-central-1"
    TAG: "1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ndla .
      - docker tag ndla:latest 028339193837.dkr.ecr.eu-central-1.amazonaws.com/ndla:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 028339193837.dkr.ecr.eu-central-1.amazonaws.com/ndla:latest