// <auto-generated />
using ConceptsMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ConceptsMicroservice.Migrations
{
    [DbContext(typeof(ConceptsContext))]
    partial class ConceptsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ConceptsMicroservice.Models.ConceptItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Created");

                    b.Property<long>("ExternalId");

                    b.Property<string>("Language");

                    b.Property<string>("SupportedLanguages");

                    b.Property<string>("Title");

                    b.Property<string>("Updated");

                    b.HasKey("Id");

                    b.ToTable("ConceptsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
